### PR TITLE
add stubbed tests in testthat/test-aaa.R

### PR DESCRIPTION
**Pull request by mpadge**
### Overview

This provides a skeleton for stubbing tests to avoid the timeout issues. This is only a temporary solution while the woRld waits for [`vcr`](https://github.com/ropensci/vcr), which will make this much easier, but your timeout issues are gargantuan (having personally experience it now!) and evidently need instant resolution.

### Notes

The simple `stub.R` function can only stub functions one environment down, effectively requiring recursive stubbing to ensure full testing. This is a pain in the proverbial, but i'm not sure how `vcr` is going to handle this either? Anyway, the added code demonstrates two recursive levels, as a sketch on the way up to the full recursive
```
`get_storms()` -> `build_archive_df()` -> `extract_storms()` -> `get_url_contents()`
```
You can simply switch on
```
trace ( curl::curl_fetch_memory, exit = function() { })
```
prior to running tests to check that this really does stub out the `httr::GET` calls. Note the `TODO` comments to re-insert the `if (test_all)` statements in a working version - current version stubs at all times; when switched on, stubbing will only happen in non-specified environments (like CRAN).

### Conclusion

This PR circumvents test failures due to timeout errors, and in doing so replaces a mere handful of lines of test code with ... 58 lines plus several more files. It sure ain't pretty, but until `vcr` emeges it's about all we got to go on.

### CODE REVIEW

**Comment by timtrice** [comment]
Mark, 

I'm getting inconsistent failures unrelated (I believe) to your modifications. Locally, in Travis and in Appveyor it's a consistent message:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
```

Is this similar to what you were seeing? I've seen it in the `fstadv` tests and `prblty` tests. The `discus` tests pass consistently (so far) which essentially are the same process.

I'm so tempted to just do basic tests for functionality. What a huge PITA...

**Comment by timtrice** [comment]
As I posted the last comment both the `fstadv` and `prblty` products pass but now `public` fails...

**Comment by timtrice** [comment]
Mark, to avoid reaching the end of my wits I've [sought advice](https://stackoverflow.com/questions/44527162/handling-inconsistent-test-results-when-scraping-a-fluctuating-website) on managing these tests. I'm at a loss on how to proceed with this other than just testing basic functionality. IMO this seems to have taken far more effort and resources than necessary.

**Comment by mpadge** [comment]
Tim, I feel your frustration! The server i need for [`osmdata`](https://github.com/ropensci/osmdata) ain't nearly as flaky as your `nhc` server, but the tests were nowhere near reliable enough for cran - a constant plague of `Timeout was reached` errors, regardless of `httr::timeout(freaking infinity)`. I have the slight advantage that the server i need at least gives a status message that can be queried - yours doesn't.

In short: My problem wasn't as severe, yet my only solution after a similar degree of exasperation, was to stub out all the actual `httr::GET` calls in tests for CRAN. I can still run them live on `travis` - but generally don't on `appveyor` because it also tends to be flaky. Anyway, I haven't looked back since then, and forgot the pain of having had to do this as soon as it starting working nicely.

While we all wait for `vcr`, a potentially neater option might be [`webmockr`](https://github.com/ropensci/webmockr), for which you could ask @sckott for advice

**Pull request closed without merging**
