### PR TITLE
Reworked native pipes in fstadv file

### PR DESCRIPTION
**Pull request by SimonAytes**
### Overview

What problem or feature request does this pull request resolve?

### Issues Addressed

 * #

### Changes Addressed/Proposed

 * 

### Reproducible Examples

Demonstrate how the new code performs.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

### Tests

Include test cases, and expected output

### CODE REVIEW

**Comment by SimonAytes** [comment]
(5/3) Addressing test failure issues. Pull request is in progress, **not ready to merge.**

Files will be re-committed to address native pipe-related test failures.

**Comment by elinw** [comment]
@SimonAytes  okay so the updated main has a lot of your stuff plus mine. You may want to check over the remaining differences.  I took a fair number of pipes out but we can also slowly add them back when we are sure they work as intended.

**Comment by elinw** [comment]
@SimonAytes  okay so the updated main has a lot of your stuff plus mine. You may want to check over the remaining differences.  I took a fair number of pipes out but we can also slowly add them back when we are sure they work as intended.

**Comment by elinw** [comment]
These changes have all been made, thanks!

**Pull request closed without merging**
